#define INP_IMAGE_SIZE 32
#define INP_IMAGE_CHANNEL 1
#define OUT_IMAGE_SIZE_C1 28
#define OUT_IMAGE_SIZE_P1 14
#define OUT_IMAGE_SIZE_C2 10
#define OUT_IMAGE_SIZE_P2 5

#define OUT_IMAGE_SIZE_F1_IN  400
#define OUT_IMAGE_SIZE_F1_OUT 120

#define OUT_IMAGE_SIZE_F2_IN  120
#define OUT_IMAGE_SIZE_F2_OUT 84

#define OUT_IMAGE_SIZE_F3_IN  84
#define OUT_IMAGE_SIZE_F3_OUT  10

#define OUT_SOFTMAX 10

#define FILTER_IN_CHANNEL_C1 1
#define FILTER_OUT_CHANNEL_C1 6
#define FILTER_SIZE_C1 5
#define STRIDE_C1 1


#define FILTER_IN_CHANNEL_C2 6
#define FILTER_OUT_CHANNEL_C2 16
#define FILTER_SIZE_C2 5
#define STRIDE_C2 1

#define STRIDE_P 2

#define FILTER_SIZE_P 2

